# Generated by Django 2.2.28 on 2025-12-13 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20251213_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 13, 22, 42, 51, 294808), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 13, 22, 42, 51, 296817), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confrim', models.BooleanField(verbose_name='Подтвержден')),
                ('ordered', models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 13, 22, 42, 51, 296817), verbose_name='Заказан')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'Orders',
                'ordering': ['-id'],
            },
        ),
    ]
