# Generated by Django 2.2.28 on 2025-12-17 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20251213_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 17, 14, 28, 22, 880091), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 17, 14, 28, 22, 880091), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 17, 14, 28, 22, 880091), verbose_name='Заказан'),
        ),
    ]
