# Generated by Django 2.2.28 on 2025-12-19 14:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_auto_20251218_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 17, 30, 21, 739275), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 17, 30, 21, 739275), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 17, 30, 21, 739275), verbose_name='Заказан'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Плохо'), (2, 'Удовлетворительно'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=3, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 17, 30, 21, 741230), verbose_name='Создан')),
                ('updated', models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 17, 30, 21, 741230), verbose_name='Изменён')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'db_table': 'Reviews',
                'ordering': ['-id'],
            },
        ),
    ]
